# Generated by Django 4.0 on 2021-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
