# Generated by Django 4.0 on 2021-12-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='dob',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='num',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='passwd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='pname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='pnum',
            field=models.CharField(default='', max_length=20),
        ),
    ]
